#draw_bold_text_with_bright_colors = true
#import = [ "~/.config/alacritty/catppuccin/catppuccin-mocha.yml" ]

# [env]
# TERM = "xterm-256color"
[colors]
    # Default colors
    [colors.primary]
        # background = "#0B161E" # base
        background = "#1a1d21" # base

[window]
opacity = 0.96
title = "Alacritty"

[window.padding]
x = 6
y = 6

#   [window.class]
#   instance = "Alacritty"
#   general = "Alacritty"

# [scrolling]
# history = 5_000

[font]
size = 11.0

  [font.normal]
  family = "iosevka nerd font"
  style = "Regular"

  [font.bold]
  family = "iosevka nerd font"
  style = "Bold"

  [font.italic]
  family = "iosevka nerd font"
  style = "Italic"

  [font.bold_italic]
  family = "iosevka nerd font"
  style = "Bold Italic"

  [font.offset]
  x = 0
  y = 1

# [[key_bindings]]
# key = "Return"
# mods = "Control"
# action = "None"

# [[key_bindings]]
# key = "V"
# mods = "Alt"
# action = "Paste"

# [[key_bindings]]
# key = "C"
# mods = "Alt"
# action = "Copy"

# [[key_bindings]]
# key = "Insert"
# mods = "Shift"
# action = "PasteSelection"

# [[key_bindings]]
# key = "Key0"
# mods = "Control"
# action = "ResetFontSize"

# [[key_bindings]]
# key = "Equals"
# mods = "Control"
# action = "IncreaseFontSize"

# [[key_bindings]]
# key = "Minus"
# mods = "Control"
# action = "DecreaseFontSize"

# [[key_bindings]]
# key = "Minus"
# mods = "Control"
# action = "DecreaseFontSize"

# [[key_bindings]]
# key = "Paste"
# action = "Paste"

# [[key_bindings]]
# key = "Copy"
# action = "Copy"

# [[key_bindings]]
# key = "L"
# mods = "Control"
# action = "ClearLogNotice"

# [[key_bindings]]
# key = "F"
# mods = "Control"
# chars = "nvim $(find  ~/Devel ~/zinstaller ~/.config -maxdepth 1  -type d -print | fzf)\r"

# [[key_bindings]]
# key = "L"
# mods = "Control"
# chars = "\f"

# [[key_bindings]]
# key = "PageUp"
# mods = "Shift"
# action = "ScrollPageUp"
# mode = "~Alt"

# [[key_bindings]]
# key = "PageDown"
# mods = "Shift"
# action = "ScrollPageDown"
# mode = "~Alt"

# [[key_bindings]]
# key = "Home"
# mods = "Shift"
# action = "ScrollToTop"
# mode = "~Alt"

# [[key_bindings]]
# key = "End"
# mods = "Shift"
# action = "ScrollToBottom"
# mode = "~Alt"

