format = """
[█](#15202B)\
$username\
[](bg:#192734 fg:#15202B)\
$directory\
[](fg:#192734 bg:#22303C)\
$git_branch\
$git_status\
[](fg:#22303C bg:#06969A)\
$c\
$elixir\
$elm\
$golang\
$haskell\
$java\
$julia\
$nodejs\
$nim\
$rust\
$scala\
[](fg:#06969A bg:#33658A)\
$docker_context\
[ ](fg:#33658A)\
"""

# Disable the blank line at the start of the prompt
add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#15202B"
style_root = "bg:#15202B"
format = '[$user ]($style)'

[directory]
style = "bg:#192734"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
#06969A 
[c]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = ""
style = "bg:#22303C"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#22303C"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ♥ $time ]($style)'
